
DROP TABLE distribucion_gasto CASCADE CONSTRAINTS;

DROP TABLE gasto CASCADE CONSTRAINTS;

DROP TABLE grupo CASCADE CONSTRAINTS;

DROP TABLE participante CASCADE CONSTRAINTS;

DROP TABLE usuario CASCADE CONSTRAINTS;

DROP SEQUENCE distribucion_gasto_seq;

DROP SEQUENCE gasto_seq;

DROP SEQUENCE grupo_seq;

DROP SEQUENCE participante_seq;

DROP SEQUENCE usuario_seq;